[package]
name = "wau"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]
default = ["curseforge", "github", "tukui", "wowinterface", "wago"]
curseforge = ["libwau/curseforge"]
github = ["libwau/github"]
tukui = ["libwau/tukui"]
wowinterface = ["libwau/wowinterface"]
wago = ["libwau/wago"]

[dependencies]
libwau = { path = "../libwau", default-features = false }

clap = { version = "4", features = ["derive"] }
thiserror = "2"
tokio = { workspace = true, features = ["fs"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
inquire = "0.9"
indicatif = "0.18"
owo-colors = "4"

[dev-dependencies]
tempfile = "3"
