name: build
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The operating system to run the job on"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
  workflow_call:
    inputs:
      runs-on:
        description: "The operating system to run the job on"
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{inputs.runs-on}}
    steps:
      - uses: actions/checkout@v4
      - name: cargo-build
        run: cargo build --verbose
