name: snyk-check-code
on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The operating system to run the job on"
        required: true
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
  workflow_call:
    inputs:
      runs-on:
        description: "The operating system to run the job on"
        required: true
        type: string

jobs:
  snyk:
    runs-on: ${{inputs.runs-on}}
    steps:
      - uses: actions/checkout@v4

      - name: snyk-setup
        uses: snyk/actions/setup@0.4.0

      - name: snyk-auth
        run: snyk auth ${{secrets.SNYK_TOKEN}}

        # Runs Snyk Code (SAST) analysis
      - name: snyk-code-test
        run: snyk code test --sarif > snyk-code.sarif

        # Runs Snyk Open Source (SCA) analysis and uploads result to Snyk
      - name: snyk-monitor
        run: snyk monitor --all-projects

      - name: upload-security-report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
