name: Test and coverage

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - name: Build cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov
      - name: Run tests
        run: cargo test --all-features --verbose
      - name: Generate coverage report (libwau)
        run: |
          cargo llvm-cov --all-features -p libwau --lcov --output-path lcov-libwau.info
      - name: Generate coverage report (wau)
        run: |
          cargo llvm-cov --all-features -p wau --lcov --output-path lcov-wau.info
      - name: Upload libwau coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: ./lcov-libwau.info
          flags: libwau
          name: libwau
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload wau coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          files: ./lcov-wau.info
          flags: wau
          name: wau
          fail_ci_if_error: false
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
