[package]
name = "libwau"
version.workspace = true
authors.workspace = true
description.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]
default = ["curseforge", "github", "tukui", "wowinterface", "wago", "git"]
curseforge = []
github = []
tukui = []
wowinterface = []
wago = []
git = []

[dependencies]
thiserror = "2"
tracing = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
url = "2"
chrono = { version = "0.4", features = ["serde"] }
tokio = { workspace = true, features = ["fs", "time", "process"] }
reqwest = { version = "0.13", default-features = false, features = ["gzip", "rustls", "stream"] }
zip = { version = "8", default-features = false, features = ["deflate"] }
async-trait = "0.1"
futures-util = "0.3"
frizbee = "0.13"
toml = "1"
dirs = "7"

[dev-dependencies]
tempfile = "3"
mockito = "1"
